ci: Retry "gem fetch"

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -27,7 +27,17 @@ jobs:
           NAME: ${{ inputs.name }}
           VERSION: ${{ inputs.version }}
         run: |
-          gem fetch ${NAME}:${VERSION}
+          # "gem fetch" may be failed if this workflow is submitted by
+          # rubygems.org's webhook because the target gem isn't
+          # registered on rubygems.org yet.
+          n_tries=0
+          while ! gem fetch ${NAME}:${VERSION}; then
+            n_tries=$[n_tries + 1]
+            if [ ${n_tries} -gt 5 ]; then
+              exit 1
+            fi
+            sleep 10
+          done
           gem specification ${NAME}-${VERSION}.gem > spec.yaml
           is_extension=$(ruby -e 'puts !Gem::Specification.from_yaml(ARGF).extensions.empty?' spec.yaml)
           echo "is-extension=${is_extension}" >> ${GITHUB_OUTPUT}
